input_csvs_folder: datasets
# exclude_datasets: ab21.csv
split_randomly: ab21.csv,hutchinson2023enhancement_top200tm1_igg.csv,jetha2019homology_RT.csv,pdgf38.csv

result_folder: our_flashabb
skip_existing_results: true

# n_cpu: 4 # number of CPUs to use for descriptors calculation and AutoML, default all available

predefined_descriptors:
  folder: /storage/antibody_data/PairedStructures/kitAb/our_flashabb/descriptors
  allowed_suffixes:
    - _flashabb_1
    - _flashabb_2
    - _flashabb_3