input_csvs_folder: datasets_ginkgo_no_hc_lc
# exclude_datasets: ab21.csv

result_folder: propermab_abb2_ginkgo_no_hc_lc
skip_existing_results: true

# n_cpu: 4 # number of CPUs to use for descriptors calculation and AutoML, default all available

predefined_descriptors:
  folder: /storage/antibody_data/PairedStructures/kitAb/descriptors_propermab_abb2/
  allowed_suffixes:
    - _abb2_1_propermab
    - _abb2_2_propermab
    - _abb2_3_propermab