# AutoML on precomputed kitAb descriptors (minimal feature set).
inputs:
  datasets_dir: datasets
  predefined_descriptors_dir: /storage/antibody_data/PairedStructures/kitAb/descriptors_our_abb2_minimal_features_baseline
  split_randomly:
    - ab21
    - hutchinson2023enhancement_top200tm1_igg
    - jetha2019homology_RT
    - pdgf38

run:
  output_dir: our_abb2_minimal_features_baseline
  skip_existing_results: true

structure_prediction:
  enabled: false

descriptors:
  enabled: false

automl:
  enabled: true
