input_csvs_folder: datasets_example

split_randomly: ab21.csv,hutchinson2023enhancement_top200tm1_igg.csv,jetha2019homology_RT.csv,pdgf38.csv

result_folder: scenario1

structure_prediction:
  model: abb3 # abb2
  device: 0 # 1; 0,3
  runs: 1 # number of runs for structure prediction, default 1. Use multiple runs to check reproducibility

stability_features: Tm,Tm2 # for target_Tm, target_Tm2
# n_cpu: 4 # number of CPUs to use for descriptors calculation and AutoML, default all available