input_csvs_folder: datasets
split_randomly: ab21.csv,hutchinson2023enhancement_top200tm1_igg.csv,jetha2019homology_RT.csv,pdgf38.csv

input_structures_folder: structures_abb2

result_folder: our_abb2_minimal_features_baseline

# n_cpu: 4 # number of CPUs to use for descriptors calculation and AutoML, default all available

structures_processing:
  renumber_imgt: False
  minimize: False

include_features:
  - protein_pi
  - cdr3_length
  - hyd_score
  - charge_symmetry
  - pos_patch_cdr
  - neg_patch_cdr
  - nonpolar_patch_cdr
  - neg_all_sasa
  - pos_all_sasa
  - hyd_all_sasa
  - aro_all_sasa