# AutoML on precomputed ProperMAb ABB2 descriptors (Ginkgo, no HC/LC).
inputs:
  datasets_dir: datasets_ginkgo_no_hc_lc
  predefined_descriptors_dir: /storage/antibody_data/PairedStructures/kitAb/descriptors_propermab_abb2/

run:
  output_dir: propermab_abb2_ginkgo_no_hc_lc
  skip_existing_results: true

structure_prediction:
  enabled: false

descriptors:
  enabled: false

automl:
  enabled: true
