# AutoML on precomputed TAP descriptors.
inputs:
  datasets_dir: datasets
  predefined_descriptors_dir: /storage/antibody_data/PairedStructures/kitAb/descriptors_tap
  split_randomly:
    - ab21
    - hutchinson2023enhancement_top200tm1_igg
    - jetha2019homology_RT
    - pdgf38

run:
  output_dir: tap_again

structure_prediction:
  enabled: false

descriptors:
  enabled: false

automl:
  enabled: true
