input_csvs_folder: datasets
# exclude_datasets: ab21.csv
split_randomly: ab21.csv,hutchinson2023enhancement_top200tm1_igg.csv,jetha2019homology_RT.csv,pdgf38.csv

result_folder: tap_again

# n_cpu: 4 # number of CPUs to use for descriptors calculation and AutoML, default all available

predefined_descriptors:
  folder: /storage/antibody_data/PairedStructures/FASTAb/descriptors_tap